[package]
name = "boreal"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.20"
regex = "1"
printpdf = "0.3.4"
lopdf = "0.26.0"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
csv = "1.1"

[[bin]]
name = "boreal"
path = "src/mainReadExcel.rs"